promise 几大模块
1. 三大状态
2. 执行器函数立即执行
3. 实例有then方法
4. 发布订阅，解决异步调用
5. 链式调用
6. resolvePromise 兼容 其它promise库
7. then 的穿透
8. 规范测试

promise A+规范 有什么用？？
所有的实现都要基于这个 文档

promise 被es6 内置了
但是在低版本浏览器不支持，比如ie，需要polyfill => es6-promise

解决异步问题，回调地狱，使得代码更为简洁。
多个异步并发请求，希望拿到最后的结果

缺点：还是基于回调

promise有三个状态
resolve、reject、pending（默认）

promise是一个类
new的时候 需要传入一个执行器，接受两个参数，resolve、reject
执行器 默认是立即执行的

每一个实例有一个 then 方法，两个参数，一个是成功的回调，一个是失败的回调
同一个promise实例可以then多次
每次then完之后，就会返回一个 新的 promise，注意不是返回 this（不符合规范，一个实例不可能既成功又失败，比如上一次是失败，但是返回一个普通值，会走下一个then的成功）

如果执行函数的时候发生了异常，走的失败 reject

promise如果一旦失败，就不能再失败，反之亦然
只有等待态的时候才能更改状态

================
内部设计到发布订阅模式

如果调用then的时候，状态是PENDING，需要先把成功和失败的回调存储起来，稍后调用resolve或
reject的时候重新执行

=================
看实例有没有 then 方法，知道是不是 promise

================
链式调用
解决代码的嵌套执行

promise成功和失败回调函数的返回值 可以传递到外层的下一个then
- 如果返回的是 普通值 如 return 100 | undefined，传递到下一次的成功回调，不是错误，不是promise，那就是普通值
- 返回promise，会采用 promise 的状态，执行promise，拿到结果，决定走下一次的 then的成功还是失败
- 出错，传递到下一个 then的 错误回调函数，如果离自己最近的 then没有错误处理，会向下找 

====================

then 的返回值 x 和 promise2 如果是同一个值 就报错：类型错误
循环引用，自己等待自己完成，不合理

====================

resolvePromise
判断很严格，要兼容其他promise库

x 是对象或者是函数才可能是一个 promise，因为别人定义的promise可以是一个函数
如果x不是对象或者函数，就是普通值，直接成功

x.then 可能会有异常，因为别人定义的 then 可以一取值的时候就报错
Object.defineProperty(x, 'then', {
    get: function() {
        <!-- 调用成功 -->
        return new Error()
    }
})

===============
穿透
onFulfilled和onRejected是必选参数，可以不写
p.then().then().then(data => {})

==============
规范测试
promises-aplus-tests 库全局安装 测试
Promise需要暴露一个 defer deferred 函数，测试的入口

==============
延迟对象 defer
解决一层嵌套
return new Promise 可以省略不写了
调用 Promise.defer() 就可以了
